name: vscodeserver
run-name: ${{ github.actor }} runs server
on: workflow_dispatch
jobs:
  vs-code-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
      - run: tar -xf vscode_cli.tar.gz
      - run: source ./build.sh
      - run: ./code tunnel --accept-server-license-terms --name the-infinitys_tunnel
